package vistas;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author Frank Paucar
 */
public class Configuraciones extends javax.swing.JDialog {

    CardLayout cardLayout;
    
    public Configuraciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cardLayout = (CardLayout)(paneles.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paneles = new javax.swing.JPanel();
        pnEmpresa = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        pnHabitacion = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbHabitacionesRegistradas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbEstadosHabitacion = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbTiposHabitacion = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btGuardarHab = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btGuardarTipo = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btGuardarEstado = new javax.swing.JButton();
        txNumHab = new javax.swing.JTextField();
        cbTipoHab = new javax.swing.JComboBox<>();
        txTipoHab = new javax.swing.JTextField();
        txPrecioDiaHab = new javax.swing.JTextField();
        txEstadoHab = new javax.swing.JTextField();
        lbColorHab = new javax.swing.JLabel();
        btElegirColor = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnServicio = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbServiciosRegistradas = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbUM = new javax.swing.JTable();
        txPrecioServicio = new javax.swing.JTextField();
        cbUM = new javax.swing.JComboBox<>();
        btGuardarUM = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txUM = new javax.swing.JTextField();
        txServicio = new javax.swing.JTextField();
        btGuardarServicio1 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        txAbrevUM = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        pnLugar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txProvincia = new javax.swing.JTextField();
        btGuardarProvincia = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tbProvincias = new javax.swing.JTable();
        cbDepto = new javax.swing.JComboBox<>();
        jLabel50 = new javax.swing.JLabel();
        btGuardarDepto = new javax.swing.JButton();
        cbPais = new javax.swing.JComboBox<>();
        jLabel49 = new javax.swing.JLabel();
        txDepto = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tbDepto = new javax.swing.JTable();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        btGuardarPais = new javax.swing.JButton();
        txPais = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        tbPais = new javax.swing.JTable();
        pnCargo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbCargos = new javax.swing.JTable();
        jLabel45 = new javax.swing.JLabel();
        txSueldo = new javax.swing.JTextField();
        btGuardarCargo = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        txCargo = new javax.swing.JTextField();
        pnAbout = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 250, 253));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 552));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(92, 108, 133));
        jLabel1.setText("Esta empresa");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(92, 108, 133));
        jLabel2.setText("Habitaciones");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(92, 108, 133));
        jLabel4.setText("Servicios");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(92, 108, 133));
        jLabel10.setText("Lugares");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(92, 108, 133));
        jLabel19.setText("Acerca de");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 130, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(92, 108, 133));
        jLabel20.setText("Cargos");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 30));

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(670, 490));

        paneles.setPreferredSize(new java.awt.Dimension(630, 490));
        paneles.setLayout(new java.awt.CardLayout());

        pnEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        pnEmpresa.setPreferredSize(new java.awt.Dimension(630, 490));
        pnEmpresa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(8, 37, 69));
        jLabel6.setText("Informacion acerca de la empresa");
        pnEmpresa.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(53, 75, 99));
        jLabel14.setText("RUC");
        pnEmpresa.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(60, 80, 102));
        pnEmpresa.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 25));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(53, 75, 99));
        jLabel15.setText("Denominacion o razón social");
        pnEmpresa.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(53, 75, 99));
        jLabel16.setText("Dirección");
        pnEmpresa.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(53, 75, 99));
        jLabel17.setText("Teléfono");
        pnEmpresa.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 20));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(53, 75, 99));
        jLabel18.setText("Pagina Web");
        pnEmpresa.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 20));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(60, 80, 102));
        jButton1.setText("Guardar datos");
        pnEmpresa.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 110, 30));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(60, 80, 102));
        pnEmpresa.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 610, 25));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(60, 80, 102));
        pnEmpresa.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 150, 25));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(60, 80, 102));
        pnEmpresa.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 610, 25));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(60, 80, 102));
        pnEmpresa.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 610, 25));

        paneles.add(pnEmpresa, "pnEmpresa");

        jScrollPane4.setBorder(null);

        pnHabitacion.setBackground(new java.awt.Color(255, 255, 255));
        pnHabitacion.setMinimumSize(new java.awt.Dimension(630, 700));
        pnHabitacion.setPreferredSize(new java.awt.Dimension(630, 700));
        pnHabitacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(8, 37, 69));
        jLabel21.setText("Configuracion de las habitaciones");
        pnHabitacion.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(3, 32, 65));
        jLabel5.setText("Habitaciones Registradas");
        pnHabitacion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(3, 32, 65));
        jLabel22.setText("Tipos de Habitacion");
        pnHabitacion.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 20));

        jLabel23.setForeground(new java.awt.Color(53, 75, 99));
        jLabel23.setText("Numero de habitacion");
        pnHabitacion.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, 25));

        tbHabitacionesRegistradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbHabitacionesRegistradas);

        pnHabitacion.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 125, 590, 150));

        tbEstadosHabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbEstadosHabitacion);

        pnHabitacion.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 590, 110));

        tbTiposHabitacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbTiposHabitacion);

        pnHabitacion.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 590, 105));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(3, 32, 65));
        jLabel24.setText("Estados de habitacion");
        pnHabitacion.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, 20));

        jLabel25.setForeground(new java.awt.Color(53, 75, 99));
        jLabel25.setText("Tipo de habitacion");
        pnHabitacion.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 110, 25));

        btGuardarHab.setForeground(new java.awt.Color(3, 32, 65));
        btGuardarHab.setText("Guardar habitacion");
        pnHabitacion.add(btGuardarHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 140, 25));

        jLabel26.setForeground(new java.awt.Color(53, 75, 99));
        jLabel26.setText("Tipo");
        pnHabitacion.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 325, 50, 25));

        jLabel27.setForeground(new java.awt.Color(53, 75, 99));
        jLabel27.setText("Precio por dia");
        pnHabitacion.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 325, 90, 25));

        btGuardarTipo.setForeground(new java.awt.Color(3, 32, 65));
        btGuardarTipo.setText("Guardar tipo");
        pnHabitacion.add(btGuardarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 325, 140, 25));

        jLabel28.setForeground(new java.awt.Color(53, 75, 99));
        jLabel28.setText("Estado");
        pnHabitacion.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 515, 50, 25));

        jLabel29.setForeground(new java.awt.Color(53, 75, 99));
        jLabel29.setText("Color");
        pnHabitacion.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 515, 40, 25));

        btGuardarEstado.setForeground(new java.awt.Color(3, 32, 65));
        btGuardarEstado.setText("Guardar estado");
        pnHabitacion.add(btGuardarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 515, 140, 25));
        pnHabitacion.add(txNumHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 50, 25));

        cbTipoHab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnHabitacion.add(cbTipoHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 110, 25));
        pnHabitacion.add(txTipoHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 325, 110, 25));
        pnHabitacion.add(txPrecioDiaHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 325, 120, 25));
        pnHabitacion.add(txEstadoHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 515, 110, 25));

        lbColorHab.setBackground(new java.awt.Color(255, 51, 51));
        lbColorHab.setForeground(new java.awt.Color(102, 102, 102));
        lbColorHab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 75, 99)));
        lbColorHab.setOpaque(true);
        pnHabitacion.add(lbColorHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 515, 60, 25));

        btElegirColor.setText("Elegir color");
        btElegirColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btElegirColorActionPerformed(evt);
            }
        });
        pnHabitacion.add(btElegirColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 515, -1, 25));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnHabitacion.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        jScrollPane4.setViewportView(pnHabitacion);

        paneles.add(jScrollPane4, "pnHabitacion");

        pnServicio.setBackground(new java.awt.Color(255, 255, 255));
        pnServicio.setPreferredSize(new java.awt.Dimension(630, 490));
        pnServicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(8, 37, 69));
        jLabel30.setText("Configuracion de los servicios");
        pnServicio.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(3, 32, 65));
        jLabel31.setText("Servicios Registradas");
        pnServicio.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        jLabel32.setForeground(new java.awt.Color(53, 75, 99));
        jLabel32.setText("UM");
        pnServicio.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 30, 25));

        tbServiciosRegistradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tbServiciosRegistradas);

        pnServicio.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 125, 590, 150));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(3, 32, 65));
        jLabel33.setText("Unidades de Medida (UM)");
        pnServicio.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 20));

        jLabel34.setForeground(new java.awt.Color(53, 75, 99));
        jLabel34.setText("Tipo");
        pnServicio.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 325, 50, 25));

        jScrollPane7.setBorder(null);

        tbUM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(tbUM);

        pnServicio.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 590, 120));
        pnServicio.add(txPrecioServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 65, 25));

        cbUM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnServicio.add(cbUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 75, 25));

        btGuardarUM.setForeground(new java.awt.Color(3, 32, 65));
        btGuardarUM.setText("Guardar UM");
        btGuardarUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarUMActionPerformed(evt);
            }
        });
        pnServicio.add(btGuardarUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 325, 140, 25));

        jLabel35.setForeground(new java.awt.Color(53, 75, 99));
        jLabel35.setText("Servicio");
        pnServicio.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 60, 25));

        jLabel36.setForeground(new java.awt.Color(53, 75, 99));
        jLabel36.setText("Precio");
        pnServicio.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 40, 25));
        pnServicio.add(txUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 325, 120, 25));
        pnServicio.add(txServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 100, 25));

        btGuardarServicio1.setForeground(new java.awt.Color(3, 32, 65));
        btGuardarServicio1.setText("Guardar servicio");
        btGuardarServicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarServicio1ActionPerformed(evt);
            }
        });
        pnServicio.add(btGuardarServicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 140, 25));

        jLabel37.setForeground(new java.awt.Color(53, 75, 99));
        jLabel37.setText("Abreviacion");
        pnServicio.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 325, 80, 25));
        pnServicio.add(txAbrevUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 325, 80, 25));

        paneles.add(pnServicio, "pnServicio");

        jScrollPane10.setBorder(null);
        jScrollPane10.setPreferredSize(new java.awt.Dimension(630, 750));

        pnLugar.setBackground(new java.awt.Color(255, 255, 255));
        pnLugar.setPreferredSize(new java.awt.Dimension(630, 750));
        pnLugar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(8, 37, 69));
        jLabel8.setText("Configuracion de lugares");
        pnLugar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(3, 32, 65));
        jLabel47.setText("Departamentos");
        pnLugar.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, 20));

        jLabel48.setForeground(new java.awt.Color(53, 75, 99));
        jLabel48.setText("Departamento");
        pnLugar.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 90, 25));
        pnLugar.add(txProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 110, 25));

        btGuardarProvincia.setForeground(new java.awt.Color(3, 32, 65));
        btGuardarProvincia.setText("Guardar provincia");
        btGuardarProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarProvinciaActionPerformed(evt);
            }
        });
        pnLugar.add(btGuardarProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 140, 25));

        tbProvincias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(tbProvincias);

        pnLugar.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 125, 590, 150));

        cbDepto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnLugar.add(cbDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 100, 25));

        jLabel50.setForeground(new java.awt.Color(53, 75, 99));
        jLabel50.setText("Provincia");
        pnLugar.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 60, 25));

        btGuardarDepto.setForeground(new java.awt.Color(3, 32, 65));
        btGuardarDepto.setText("Guardar depto");
        btGuardarDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarDeptoActionPerformed(evt);
            }
        });
        pnLugar.add(btGuardarDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 140, 25));

        cbPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnLugar.add(cbPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 100, 25));

        jLabel49.setForeground(new java.awt.Color(53, 75, 99));
        jLabel49.setText("Pais");
        pnLugar.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 50, 25));
        pnLugar.add(txDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 130, 25));

        jLabel51.setForeground(new java.awt.Color(53, 75, 99));
        jLabel51.setText("Departamento");
        pnLugar.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 90, 25));

        tbDepto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane11.setViewportView(tbDepto);

        pnLugar.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 355, 590, 150));

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(3, 32, 65));
        jLabel52.setText("Provincias");
        pnLugar.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        jLabel53.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(3, 32, 65));
        jLabel53.setText("Departamentos");
        pnLugar.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 20));

        btGuardarPais.setForeground(new java.awt.Color(3, 32, 65));
        btGuardarPais.setText("Guardar pais");
        btGuardarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarPaisActionPerformed(evt);
            }
        });
        pnLugar.add(btGuardarPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 140, 25));
        pnLugar.add(txPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 180, 25));

        jLabel55.setForeground(new java.awt.Color(53, 75, 99));
        jLabel55.setText("Pais");
        pnLugar.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 40, 25));

        tbPais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane12.setViewportView(tbPais);

        pnLugar.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 590, 150));

        jScrollPane10.setViewportView(pnLugar);

        paneles.add(jScrollPane10, "pnLugar");

        pnCargo.setBackground(new java.awt.Color(255, 255, 255));
        pnCargo.setPreferredSize(new java.awt.Dimension(630, 490));
        pnCargo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(8, 37, 69));
        jLabel7.setText("Configuracion de cargos");
        pnCargo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(3, 32, 65));
        jLabel44.setText("Cargos registrados");
        pnCargo.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        tbCargos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tbCargos);

        pnCargo.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 125, 590, 200));

        jLabel45.setForeground(new java.awt.Color(53, 75, 99));
        jLabel45.setText("Sueldo Mensual");
        pnCargo.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 100, 25));
        pnCargo.add(txSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 100, 25));

        btGuardarCargo.setForeground(new java.awt.Color(3, 32, 65));
        btGuardarCargo.setText("Guardar cargo");
        btGuardarCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarCargoActionPerformed(evt);
            }
        });
        pnCargo.add(btGuardarCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 140, 25));

        jLabel46.setForeground(new java.awt.Color(53, 75, 99));
        jLabel46.setText("Cargo");
        pnCargo.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 60, 25));
        pnCargo.add(txCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 140, 25));

        paneles.add(pnCargo, "pnCargo");

        pnAbout.setBackground(new java.awt.Color(255, 255, 255));
        pnAbout.setPreferredSize(new java.awt.Dimension(630, 490));
        pnAbout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(8, 37, 69));
        jLabel38.setText("Acerca del software");
        pnAbout.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(53, 75, 99));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel39.setText("Paucar Colonia Frank Cesar");
        pnAbout.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 200, 25));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(3, 32, 65));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("Autor : ");
        pnAbout.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 150, 20));

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(3, 32, 65));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel41.setText("Version del producto : ");
        pnAbout.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 150, 20));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(53, 75, 99));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel42.setText("v0.1 dev");
        pnAbout.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 200, 25));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/public/imagenes/acerca_de.png"))); // NOI18N
        pnAbout.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(3, 32, 65));
        jLabel43.setText("© Todos los derechos reservados ");
        jLabel43.setToolTipText("");
        jLabel43.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        pnAbout.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 300, 20));

        paneles.add(pnAbout, "pnAbout");

        jScrollPane1.setViewportView(paneles);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /************************ Inicio Cambio de paneles ************************/
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        cardLayout.show(paneles, "pnEmpresa");
    }//GEN-LAST:event_jLabel1MouseClicked
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        cardLayout.show(paneles, "pnHabitacion");
    }//GEN-LAST:event_jLabel2MouseClicked
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        cardLayout.show(paneles, "pnServicio");
    }//GEN-LAST:event_jLabel4MouseClicked
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        cardLayout.show(paneles, "pnLugar");
    }//GEN-LAST:event_jLabel10MouseClicked
    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        cardLayout.show(paneles, "pnCargo");
    }//GEN-LAST:event_jLabel20MouseClicked
    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        cardLayout.show(paneles, "pnAbout");
    }//GEN-LAST:event_jLabel19MouseClicked
    /************************ Fin Cambio de paneles ************************/
    
    private void btElegirColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btElegirColorActionPerformed
        //JColorChooser colorChooser = new JColorChooser(lbColorHab.getBackground());
        Color colorElegido = JColorChooser.showDialog(null, "Seleccione un Color", lbColorHab.getBackground());
        lbColorHab.setBackground(colorElegido);
    }//GEN-LAST:event_btElegirColorActionPerformed

    private void btGuardarUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarUMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGuardarUMActionPerformed

    private void btGuardarServicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarServicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGuardarServicio1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.out.println("JScroll1 "+jScrollPane1.getSize().width+" x "+jScrollPane1.getSize().height);
        System.out.println("Paneles "+paneles.getSize().width+" x "+paneles.getSize().height);
        //System.out.println("JScroll4 "+jScrollPane4.getSize().width+" x "+jScrollPane4.getSize().height);
        System.out.println("Panel Hab "+pnHabitacion.getSize().width+" x "+pnHabitacion.getSize().height);
        System.out.println("------------");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btGuardarCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGuardarCargoActionPerformed

    private void btGuardarProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGuardarProvinciaActionPerformed

    private void btGuardarDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarDeptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGuardarDeptoActionPerformed

    private void btGuardarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGuardarPaisActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuraciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Configuraciones dialog = new Configuraciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btElegirColor;
    private javax.swing.JButton btGuardarCargo;
    private javax.swing.JButton btGuardarDepto;
    private javax.swing.JButton btGuardarEstado;
    private javax.swing.JButton btGuardarHab;
    private javax.swing.JButton btGuardarPais;
    private javax.swing.JButton btGuardarProvincia;
    private javax.swing.JButton btGuardarServicio1;
    private javax.swing.JButton btGuardarTipo;
    private javax.swing.JButton btGuardarUM;
    private javax.swing.JComboBox<String> cbDepto;
    private javax.swing.JComboBox<String> cbPais;
    private javax.swing.JComboBox<String> cbTipoHab;
    private javax.swing.JComboBox<String> cbUM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lbColorHab;
    private javax.swing.JPanel paneles;
    private javax.swing.JPanel pnAbout;
    private javax.swing.JPanel pnCargo;
    private javax.swing.JPanel pnEmpresa;
    private javax.swing.JPanel pnHabitacion;
    private javax.swing.JPanel pnLugar;
    private javax.swing.JPanel pnServicio;
    private javax.swing.JTable tbCargos;
    private javax.swing.JTable tbDepto;
    private javax.swing.JTable tbEstadosHabitacion;
    private javax.swing.JTable tbHabitacionesRegistradas;
    private javax.swing.JTable tbPais;
    private javax.swing.JTable tbProvincias;
    private javax.swing.JTable tbServiciosRegistradas;
    private javax.swing.JTable tbTiposHabitacion;
    private javax.swing.JTable tbUM;
    private javax.swing.JTextField txAbrevUM;
    private javax.swing.JTextField txCargo;
    private javax.swing.JTextField txDepto;
    private javax.swing.JTextField txEstadoHab;
    private javax.swing.JTextField txNumHab;
    private javax.swing.JTextField txPais;
    private javax.swing.JTextField txPrecioDiaHab;
    private javax.swing.JTextField txPrecioServicio;
    private javax.swing.JTextField txProvincia;
    private javax.swing.JTextField txServicio;
    private javax.swing.JTextField txSueldo;
    private javax.swing.JTextField txTipoHab;
    private javax.swing.JTextField txUM;
    // End of variables declaration//GEN-END:variables
}
