/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Frank Paucar
 */
public class EmpresasRegistradas extends javax.swing.JDialog {

    /**
     * Creates new form EmpresasRegistradas
     */
    public EmpresasRegistradas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmEmpresas = new javax.swing.JPopupMenu();
        miElegirEmpresa = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txNombresCliReserva = new javax.swing.JTextField();
        btRegistrarEmpleado1 = new javax.swing.JButton();
        txRazonSocial = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel44 = new javax.swing.JLabel();
        txRUC = new javax.swing.JTextField();

        miElegirEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/public/imagenes/iconos/ic_enviar.png"))); // NOI18N
        miElegirEmpresa.setText("Elegir empresa");
        pmEmpresas.add(miElegirEmpresa);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 600));
        setPreferredSize(new java.awt.Dimension(650, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(650, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(8, 37, 69));
        jLabel10.setText("Empresas");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 25, -1, 35));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(53, 75, 99));
        jLabel42.setLabelFor(txRazonSocial);
        jLabel42.setText("Razon Social");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(53, 75, 99));
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/public/imagenes/iconos/ic_buscar.png"))); // NOI18N
        jLabel43.setText("Buscar");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 245, 80, 25));

        txNombresCliReserva.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txNombresCliReserva.setForeground(new java.awt.Color(60, 80, 102));
        jPanel1.add(txNombresCliReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 245, 460, 25));

        btRegistrarEmpleado1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btRegistrarEmpleado1.setForeground(new java.awt.Color(33, 29, 37));
        btRegistrarEmpleado1.setText("Registrar empresa");
        jPanel1.add(btRegistrarEmpleado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        txRazonSocial.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txRazonSocial.setForeground(new java.awt.Color(60, 80, 102));
        jPanel1.add(txRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 550, 25));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setComponentPopupMenu(pmEmpresas);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 550, 260));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(53, 75, 99));
        jLabel44.setText("N° RUC");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 20));

        txRUC.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txRUC.setForeground(new java.awt.Color(60, 80, 102));
        jPanel1.add(txRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 190, 25));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpresasRegistradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpresasRegistradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpresasRegistradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpresasRegistradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EmpresasRegistradas dialog = new EmpresasRegistradas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRegistrarEmpleado1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem miElegirEmpresa;
    private javax.swing.JPopupMenu pmEmpresas;
    private javax.swing.JTextField txNombresCliReserva;
    private javax.swing.JTextField txRUC;
    private javax.swing.JTextField txRazonSocial;
    // End of variables declaration//GEN-END:variables
}
